### ISSUE TITLE
stat_stick and skill level

### ISSUE THREAD

**Issue by srwgin** [adangtran87/gbf-weap#12]
skill levels not support 11-15 right?
I found that you did not separate lv1-10 and 11-15 except baha
what is stat_stick weapon？ cosmos weapon？
and what python -m unittest discover tests used to do？
and I am not sure this is a problem
after run script  not create weapon-optimizer.pyc files
the others has pyc files

some error
if I write weapon and summons data in fire.json
then python weapon-optimizer.py fire.json
it works fine
if I write data in 2 file fire-weapons.json fire-summons.json
when I run the script
python weapon-optimizer.py fire-weapons.json fire-summons.json
usage: weapon-optimizer.py [-h] [--list_all] config_file
weapon-optimizer.py: error: unrecognized arguments: fire-summons.json

I use this weapon data in file
      "name": "SSR Murgleis",
      "weapon_class": "normal2",
      "damage": 1374,
      "weapon_type": "sword",
      "weapon_skill": "large",
      "skill_level": 5
when I run script it is error
Traceback (most recent call last):
  File "weapon-optimizer.py", line 112, in <module>
    weapon_list = parse_weapon_from_data(config_data)
  File "weapon-optimizer.py", line 76, in parse_weapon_from_data
    weapon = WeaponNormal2(**weapon_entry['args'])
KeyError: 'args'

**Comment by adangtran87** [comment]
I've combined the json file into one file. Two files won't work anymore.

Fixed the normal 2 import.

`python -m unittest discover tests` runs the unit tests. https://docs.python.org/2.7/library/unittest.html

**Comment by adangtran87** [comment]
I've added support for SL > 10 according to 5.1 of http://gbf-english.proboards.com/thread/595/.

Stat sticks are weapons that only provide damage and no attack multiplier.
