### ISSUE TITLE
main_character

### ISSUE THREAD

**Issue by srwgin** [adangtran87/gbf-weap#13]
The following data is needed
"party": {
      "main_character": {
          "name": "Djeeta",
          "char_class": "hawkeye",
          "race": "unknown"
          "Rank": "100", //needed
          "specialty1": "Dagger"
          "specialty WPN 1 DMG Bonus": "0%" needed//0%~6% 
          "specialty2": "gun"
          "specialty WPN 2 DMG Bonus": "6%"  needed//0%~6% 
          "Class ATK Bonus": "3000"  needed//0~3000 
          "ATK Bonus": "3%"  needed//when you in party slot page check bonus icon beside class head
all bonuses the first one 
          "MAX HP": "100%"  needed// for future last stand attack modifiers
          "total summons ATK": "6872"  needed//if my_summons has several summons，this data also has several ，because main summons changed
      }

reference http://gbf.xzz.jp/

**Comment by adangtran87** [comment]
This script isn't trying to find exact damage of the setup like http://gbf.xzz.jp/. I'm trying to figure out what the best pool is for a particular party. Summon ATK, character levels would not change the weapons in the pool.

The only thing that would have an effect in weapon pool optimization is the Zenith point for weapon specialty damage boost, but that is more minor than the weapon specialty itself; also it only affects one character. If it would make a weapon swap out, leaving the previous weapon in would have negligible damage difference.
