### ISSUE TITLE
Missing Weapon Types

### ISSUE THREAD

**Issue by srwgin** [adangtran87/gbf-weap#7]
miss Normal II Strength Weapon Type
magna1 magna2 Damage Modifiers different

**Comment by srwgin** [comment]
is it possible setting a local proxy then get weapon data from game and save as json file

**Comment by adangtran87** [comment]
I don't plan on getting a users's weapon data at the moment; especially since I assume everything is on element. Maybe in the future if this script gets that far.

Magna1 and Magna2 damage modifiers being different is news to me. What is the difference? Does it add an extra % like Normal2 does?

**Comment by srwgin** [comment]
Strength as same as UK
mana I medium=3%+（SLv-1） SLv=1-10，=12%+（SLv-10）*0.5 SLv=10-15
mana II large=6%+（SLv-1） SLv=1-10，=15%+（SLv-10）*0.6 SLv=10-15
normal I large=6%+（SLv-1） SLv=1-10，=15%+（SLv-10）*0.6 SLv=10-15
normal II large=7%+（SLv-1） SLv=1-10，=16%+（SLv-10）*0.8 SLv=10-15
