### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by srwgin** [adangtran87/gbf-weap#8]
add WeaponType
    normal2 = 5
    normalls = 6
    magnals = 7
    strength = 8
    bahamut2 = 9//Sword Staff
summonsype
odin=6

1 + (Magna Weapon Modifier * Magna Summon Modifier)
1 + (Magna Weapon Last Stand Modifier * Magna Summon Modifier)
1 + ((Normal Weapon Modifier+Normal2 Weapon Modifier) * Primal Summon Modifier) + Bahamut Modifier + Bahamut2 Modifier + Character Modifier + Attack Buff
1 + (Normal Weapon Last Stand Modifier) * (Primal Summon Modifier)
1 + (Unknown Weapon Modifier * Ranko Summon Modifier) + Strength Modifier
1 + Elemental Affinity + Elemental Summon Strength + Elemental Bonus
Base Damage * Magna Weapon * Magna Last Stand * Normal Weapon* Normal Last Stand* Unknown * Elemental

**Comment by adangtran87** [comment]
Appreciate the input. I don't plan on supporting last stand weapons in this script for now. I doubt I'll implement 'bahamut2' in that fashion; will be covered in #1.
